version: "3.0"

expectations:
  population_size: 1000

actions:
  visit_num:
    run: sqlrunner:latest
      --output output/raw/visit_num.csv
      --dummy-data-file analysis/visit_num.csv
      analysis/visit_num.sql
    outputs:
      highly_sensitive:
        rows: output/raw/visit_num.csv

  make_safe:
    needs: [visit_num]
    run: python:latest python analysis/make_safe.py
    config:
      tables:
        - from: output/raw/visit_num.csv
          to: output/safe/visit_num.csv
          columns: [num_rows]
    outputs:
      moderately_sensitive:
        rows: output/safe/*.csv
